FROM python:3.8.12-slim-buster

RUN apt-get update
RUN apt-get install -y make librsvg2-bin imagemagick graphviz git

COPY requirements.txt /tmp
RUN egrep "phinx|mpmath|matplotlib" /tmp/requirements.txt > /tmp/req_min.txt
RUN pip install --upgrade pip
RUN pip install -r /tmp/req_min.txt

CMD cd /sympy/doc; make html
